<a href="https://colab.research.google.com/github/DiegoAndresCastroBahamon/dsf/blob/main/chapter_04/numpy_challenge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy Challenge

Create a NumPy ndarray object by using this list of numbers [7,8,4,5,1,2].


In [1]:
import numpy as np

numbers_list = [7, 8, 4, 5, 1, 2]
numbers_array = np.array(numbers_list)

print(numbers_array)


[7 8 4 5 1 2]


Using slicing print the elements from index 3 to the end of the array.



In [2]:
import numpy as np

numbers_list = [7, 8, 4, 5, 1, 2]
numbers_array = np.array(numbers_list)

sliced_elements = numbers_array[3:]

print(sliced_elements)


[5 1 2]


Using slicing print all the elements except the last one.

1.   Elemento de lista
2.   Elemento de lista





In [3]:
import numpy as np

numbers_list = [7, 8, 4, 5, 1, 2]
numbers_array = np.array(numbers_list)

sliced_elements = numbers_array[:-1]

print(sliced_elements)


[7 8 4 5 1]


Using slicing print the elements from index 1 to index 4 of the array.



In [4]:
import numpy as np

array = np.array([10, 20, 30, 40, 50, 60, 70])
elementsToPrint = array[1:5]

print(elementsToPrint)


[20 30 40 50]


Reshape the array into a 3 rows and 2 cols (3,2).



In [10]:
import numpy as np

array = np.array([10, 20, 30, 40, 50, 60])
array.shape = (3, 2)

print(array)


[[10 20]
 [30 40]
 [50 60]]


Print all the array elements one by one (iterating).



In [11]:
import numpy as np

array = np.array([[10, 20],
                     [30, 40],
                     [50, 60]])

for row in array:
    for element in row:
        print(element)


10
20
30
40
50
60


Create a new NumPy ndarray object by using this list of numbers [0,6,9].



In [13]:
import numpy as np

numbersList = [3, 3, 3]
newArray = np.array(numbersList)

print(newArray)


[3 3 3]


Join the two arrays.



In [38]:
import numpy as np

numbers = [7, 8, 4, 5, 1, 2]
num_array = np.array(numbers)

new_numbers = [0, 6, 9]
new_num_array = np.array(new_numbers)

concatenated_array = np.concatenate((num_array, new_num_array))

print(concatenated_array)

[7 8 4 5 1 2 0 6 9]


Using filtering print only the odd numbers of the joined array.



In [40]:
import numpy as np

numbers = [7, 8, 4, 5, 1, 2]
num_array = np.array(numbers)

new_numbers = [0, 6, 9]
new_num_array = np.array(new_numbers)

concatenated_array = np.concatenate((num_array, new_num_array))

odd_numbers = concatenated_array[concatenated_array % 2 != 0]

print(odd_numbers)

[7 5 1 9]


Sort the joined array elements.



In [41]:
import numpy as np

numbers = [7, 8, 4, 5, 1, 2]
num_array = np.array(numbers)

new_numbers = [0, 6, 9]
new_num_array = np.array(new_numbers)

concatenated_array = np.concatenate((num_array, new_num_array))

sorted_array = np.sort(concatenated_array)

print(sorted_array)


[0 1 2 4 5 6 7 8 9]


Store in an array the names of the months.



In [20]:
import numpy as np

months_array = np.array(['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'])

print(months_array)


['January' 'February' 'March' 'April' 'May' 'June' 'July' 'August'
 'September' 'October' 'November' 'December']


Split the months array in 4 periods of 3 elements each one.



In [21]:
import numpy as np

months_array = np.array(['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'])

split_periods = np.split(months_array, 4)

for period in split_periods:
    print(period)


['January' 'February' 'March']
['April' 'May' 'June']
['July' 'August' 'September']
['October' 'November' 'December']


Create an array with genre information ['F','M','F','F','M','F'].



In [22]:
import numpy as np

gender_array = np.array(['F', 'M', 'F', 'F', 'M', 'F'])

print(gender_array)


['F' 'M' 'F' 'F' 'M' 'F']


Find the indexes where the value is F.



In [23]:
import numpy as np

gender_array = np.array(['F', 'M', 'F', 'F', 'M', 'F'])

indexes_F = np.where(gender_array == 'F')[0]

print(indexes_F)


[0 2 3 5]


Store in an array the age information [18,20,19,23,19,20].



In [24]:
import numpy as np

age_array = np.array([18, 20, 19, 23, 19, 20])

print(age_array)


[18 20 19 23 19 20]


Create a filter array with values < 20.



In [25]:
import numpy as np

age_array = np.array([18, 20, 19, 23, 19, 20])

filter_array = age_array < 20

print(filter_array)


[ True False  True False  True False]


Change the 3 index element with a value of 22



In [26]:
import numpy as np

age_array = np.array([18, 20, 19, 23, 19, 20])

age_array[3] = 22

print(age_array)


[18 20 19 22 19 20]


Print the 4 index element.

In [27]:
import numpy as np

age_array = np.array([18, 20, 19, 22, 19, 20])

element_at_index_4 = age_array[3]

print(element_at_index_4)


22


In [29]:
print("Presented by: Diego Castro Bahamon / Manuel Isaias Navarro")

Presented by: Diego Castro Bahamon / Manuel Isaias Navarro
